name: Tests

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x, 22.x]
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: install corepack
        run: |
          npm install -g corepack@latest --force
          corepack enable
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Check coding standards
        if: matrix.node-version == '20.x' && matrix.os == 'ubuntu-latest'
        run: npm run lint
      - name: Test
        run: npm run ci
      # Stay on coveralls instead of codecov, since hildjj doesn't own the
      # repo directly, and it's too much work to figure out.
      - name: Coveralls Parallel
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          flag-name: node-${{ matrix.node-version }}
          path-to-lcov: ./coverage/lcov.info
          parallel: true
  finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: ./coverage/lcov.info
          parallel-finished: true
